version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - elk
      
  logstash:
    container_name: logstash
    build:
      context: ./logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: ./kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  node1:
    container_name: seeme_server
    build:
      context: ./
      target: dev
    restart: unless-stopped
    command: npm run dev
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./awsconfig.storj.json:/app/awsconfig.storj.json
      # - ./dist:/app/dist
      - log-data:/app/logs

  filebeat:
    container_name: filebeat
    build:
      context: ./filebeat/
    volumes:
      # - type: bind
      #   source: ./filebeat/filebeat.yml
      #   target: /usr/share/filebeat/filebeat.yml
      - type: volume
        source: log-data
        target: /var/log/server
    networks:
      - elk
    depends_on:
      - logstash
      # - elasticsearch

networks:
  elk:
    driver: bridge
    
volumes:
  elasticsearch:
  log-data:

# nginx:
#   container_name: seeme_nginx
#   image: nginx
#   ports:
#     - "80:80"
#   volumes:
#     - ./src/localhost-key.pem:/etc/ssl/localhost-key.pem
#     - ./src/localhost.pem:/etc/ssl/localhost.pem
#     - ./nginx.conf:/etc/nginx/nginx.conf