version: "3.7"

services:
  db:
    container_name: seeme_test_db
    image: mysql:8
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    ports:
      - 3307:3306
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ../.env.test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    # volumes:
    #   - ./dist:/app/dist
